In [3]:
import numpy as np

# Tạo mảng
a = np.array([1,2,3])

# In mảng
print(a)

# In ra 1 phần tử
element = a[1]
print(element)

[1 2 3]
2


In [5]:
# Tạo mảng 2 chiều
matrix = np.array([[1, 2, 3], [7, 8, 9], [8, 5, 2]])
print("Matrix:")
print(matrix)

# In một phần tử
element = matrix[1, 2]
print(element)

Matrix:
[[1 2 3]
 [7 8 9]
 [8 5 2]]
9


In [7]:
# Cách tạo mảng
# Tạo mảng toàn là số 0
a = np.zeros(4)
print(a)

# Tạo mảng toàn là số 1
a = np.ones(4)
print(a)

# Tạo mảng
a = np.empty(4)
print(a)

# Tạo mảng từ 0 đến 100
a = np.arange(100)
print(a)

# Tạo mảng gồm các phần tử với khoảng cách đều nhau
a = np.linspace(0, 10, num=4)
print(a)


# Xác định kiểu dữ liệu
a = np.ones(4, dtype=np.int64)
a

[0. 0. 0. 0.]
[1. 1. 1. 1.]
[1. 1. 1. 1.]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[ 0.          3.33333333  6.66666667 10.        ]


array([1, 1, 1, 1], dtype=int64)

In [13]:
# Thêm, xóa, sắp xếp mảng

# Create new array
arr = np.array([3, 1, 2, 4])
print(arr)

# Sort
arr = np.sort(arr)
print(arr)

# Sort -1
arr = np.sort(arr)[::-1]
print(arr)

# Append 1 more to the right
arr = np.append(arr, 100)
print(arr)

# Delete position
arr = np.delete(arr, 2)
print(arr)

[3 1 2 4]
[1 2 3 4]
[4 3 2 1]
[  4   3   2   1 100]
[  4   3   1 100]


In [17]:
# Tạo một mảng 2 chiều
arr = np.array([[3, 1, 2],
                [8, 6, 4],
                [9, 7, 5]])

sort_row = np.sort(arr, axis=1) # inc
print(sort_row)

sort_collumn = np.sort(arr, axis=0) # inc
print(sort_collumn)

[[1 2 3]
 [4 6 8]
 [5 7 9]]
[[3 1 2]
 [8 6 4]
 [9 7 5]]


In [21]:
# Tạo một mảng 2D
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Sử dụng các thuộc tính để lấy thông tin về mảng
dimension_number = arr.ndim  # dimension number (2 chiều)
si_ze = arr.size  # Size (tổng số phần tử, 6)
Sha_pe = arr.shape  # Shape (số hàng x số cột, (2, 3))

print("dimension number:", dimension_number)
print("Size:", si_ze)
print("Shape:", Sha_pe)

dimension number: 2
Size: 6
Shape: (2, 3)


In [23]:
# Convert data type
arr = np.array([6, 7, 8, 9, 10])
arr_float = arr.astype(float)
print(arr_float)

[ 6.  7.  8.  9. 10.]


In [33]:
# Reshaping the array
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(2,3)
print(reshaped_arr)
reshaped_arr = arr.reshape(3,2)
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [35]:
reshaped_arr = reshaped_arr.flatten() # Change to first dim
print(reshaped_arr)

[1 2 3 4 5 6]


In [37]:
# Cut the array
arr = np.array([1, 2, 3, 4, 5])

sub_arr = arr[1:4]  # Cắt từ phần tử thứ 1 đến 4
print(sub_arr) # 2 3 4 5

sub_arr = arr[:-2]  # 2 3 4
print(sub_arr)

sub_arr = arr[-3:]  # 5 
print(sub_arr)

[2 3 4]
[1 2 3]
[3 4 5]


In [39]:
#  Transpose array
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
# To transpose the array, we can use .T or the numpy.transpose() function.
transposed_arr = arr.T
print(transposed_arr)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [41]:
# Combine array
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]
